import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js 14',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
